/*Crear una tabla Vendedor */
CREATE TABLE VENDEDOR (
    CODVEND CHAR(6),
    NOMVEND VARCHAR(50),
    APEVEND VARCHAR(50),
    DOCVEND VARCHAR(10),
    CELVEND CHAR(9),
    DOMVEND VARCHAR(80),
    PRIMARY KEY (CODVEND)
);

/*Crear una tabla Vendedor */
SELECT DATABASES INTO(dbMinimarket);

CREATE TABLE CLIENTE(
    CODCLI CHAR(6),
    NOMCLI VARCHAR(50),
    APECLI VARCHAR(50),
    CELCLI CHAR(9);
    EMAILCLI VARCHAR(50);
    FECHNACCLI DATE;
    CONSTRAINT CODCLI_PK PRIMARY KEY (CODCLI)
);

CREATE TABLE VENTA(
    IDVENT int;
    FECVENT DATE;
    CODVEND CHAR(6);
    CODCLI CHAR(6);
    TIPVENT CHAR(1);
    PRIMARY KEY (IDVENT);
);

CREATE TABLE VENTA_DETALLE(
    IDVENTDET int;
    IDVENT int;
    CODPRO CHAR(6);
    CANTVENTDET int;
    PRIMARY KEY (IDVENTDET)
);

CREATE TABLE PRODUCTO(
    CODPRO CHAR(6);
    NOMPRO VARCHAR(50);
    PREPRO DECIMAL(8,2);
    STOCKPRO int,
    PRIMARY KEY (CODPRO)
);


